### ISSUE TITLE
Updates for 2020 release

### ISSUE THREAD

**Issue by dallenroberts** [vando026/ahri#6]
Hi Alain - hope you're doing well!

I just downloaded the 2020 datasets, and some of the naming conventions have changed in the Episodes dataset. These are causing problem with the read* functions.

First, it seems that the [2020 Surveillance Episodes dataset](https://data.ahri.org/index.php/catalog/988) is called "SurveillanceEpisodes.dta" instead of "SurveillanceEpisodesExtended.dta". This results in an error in readEpisodes() unless the name of the dataset is changed. Not sure how you will want to handle that in the future.

Second, some of the variable names in the Episodes data have changed in the release. For example, "Year" is now called "CalendarYear". Since "Year" is hardcoded into the the readEpisodes function, the dataset can't be loaded.

Third, the test_* functions are specific to 2019. Do you want to update those to 2020?

The HIV, MGH, and WGH datasets appear to load fine, although I haven't worked with them extensively yet.

Thanks,

Allen

**Comment by vando026** [comment]
Hi Allen, 

I too have just downloaded the 2020 datasets, and I am sure they have several name changes from the 2019 datasets. 

I was going to to run the first set of tests this week, but thanks for giving me a heads up on these issues. 

Just so you know, you can change the name of the specific datasets that you read in rather than accepting the default names.  This capability is documented at the end of https://github.com/vando026/ahri/wiki/1-Getting-started . In my case I would do something like:

` 
getFiles <- setFiles(
  folder="C:/Users/alainv/AHRI_Data/2020",
  epifile="SurveillanceEpisodes.dta")
`

But I cannot predict what happens after this. I will test out the readEpisodes function tomorrow and write some tests in the next couple of days. Speaking of which, what do you suggest around the issues of hardcoding names. For example, I could just force CalendarYear = Year, and then for every release year, rename the variables to the 2019 names.  This will have to be a once yearly reactive process with the cost of adding extra code to the read functions. Do you have an alternative approach in mind?

**Comment by dallenroberts** [comment]
Thanks for pointing out how to change the dataset names.

The solution you proposed for variable names seems like that's the only way to make sure that everyone using the AHRI data ends up with a standardized dataset with consistent variable names. I wonder if the standardization could happen on the AHRI side prior to dataset release, with communication to whoever creates the variable names. But if the variable names keep changing, it seems like there is no way to programmatically predict which of the new names will correspond to the old names. I suppose you could create a list of function arguments of variable names that each user could pass (eg: YearVar = "Year"), with defaults to the 2019 names, and then each user could update the arguments as needed for each dataset release (eg: YearVar = "CalendarYear"). It risks user error but saves you time.

I also noticed that variables like "EarliestHIVPos" and "EarliestARTInitDate" are not in the new SurveillanceEpisodes.dta dataset, so those might have to be generated from other variables. I don't actually use those for my project - I create everything related to HIV status from the HIV dataset - but I imagine they are useful for your use case.

**Comment by vando026** [comment]
Hi Allen, I made some changes. 

First, I changed the default root name of the epifile/epi_rda arguments from SurveillanceEpisodesExtended to SurveillanceEpisodes in the `setFiles` function. So you do not need to pass in the new 2020  names.  However, that means you will have to do this for the 2019 data. On my system I have to do:

`getFiles = setFiles('~/AHRI_Data/2019', epifile = "SurveillanceEpisodesExtended.dta", epi_rda="SurveillanceEpisodesExtended.Rda")`

You can run the `test_ahri_dta` on the 2019 data to make sure everything still works as expected. 

Second, I changed the `readEpisodes` function to accomodate two new variable name changes for Year and EarliestARTInitDate. I just decided to force the name changes depending on the release year, rather than making the user supply  these arguments (I am really trying to keep it simple). You can see these changes in the R/getEpisodes.R file (lines 36-55) on Github.

I also dropped EarliestHIVPos variable from the 2020 dataset as it didnt exist. This affects the  `getEverART` function, which I fixed using a different solution (but not yet tested). 

Please can you resinstall, restart and test that the `readEpisodes` and `getEpisodes` functions now work. 

The new tests for 2020 will take some time to set up as I have to redo all the test values!

But hopfully I can start work on this next week. 

Let me know how it goes. 

Alain

**Comment by dallenroberts** [comment]
Looks great - 2019 passes test_ahri_dta() with the new function arguments, and readHIVData, readEpisodes, and readHealthData all run without errors for 2020. Thanks again for taking a look at this so quickly.

Let me know when the 2020 tests are ready and I'll verify.

Allen

**Comment by vando026** [comment]
Hi Allen, i just updated the 2020 tests and I have updated the code to read the 2020 datasets. The code/test should now work for 2019 and 2020. Please reopen this issue if you run into any troubles.
